//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mathling
{
    public partial class Login
    {
        protected global::System.Web.UI.WebControls.TextBox LoginEmail;
        protected global::System.Web.UI.WebControls.TextBox LoginPassword;
        protected global::System.Web.UI.WebControls.Label ErrorMessage;
        protected global::System.Web.UI.WebControls.Button LoginBtn;

        protected global::System.Web.UI.WebControls.TextBox RegName;
        protected global::System.Web.UI.WebControls.TextBox RegEmail;
        protected global::System.Web.UI.WebControls.TextBox RegPassword;
        protected global::System.Web.UI.WebControls.HiddenField RegRole;
        protected global::System.Web.UI.WebControls.Button RegBtn;
    }
}
